---
- name: Download nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy main nginx configuration with validation
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_dest }}"
    owner: root
    group: root
    mode: '0644'
    validate: "nginx -t -c %s"

- name: Ensure nginx is running
  service:
    name: nginx
    state: restarted
    enabled: true
