---
- name: Download nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy nginx site configuration with validation
  template:
    src: "{{ nginx_site_template }}"
    dest: "{{ nginx_site_available }}"
    validate: "nginx -t -c %s"
    owner: root
    group: root
    mode: '0644'

- name: Enable nginx site
  file:
    src: "{{ nginx_site_available }}"
    dest: "{{ nginx_site_enabled }}"
    state: link

- name: Ensure nginx is running
  service:
    name: nginx
    state: restarted
    enabled: true
