---
- name: Download nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy main nginx configuration with validation
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_dest }}"
    owner: root
    group: root
    mode: '0644'
    validate: "nginx -t -c %s"

- name: Copy default site configuration with validation
  template:
    src: "{{ default_site_template }}"
    dest: "/etc/nginx/sites-available/default"
    owner: root
    group: root
    mode: '0644'

- name: Create symbolic link for default site
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link

- name: Ensure nginx is running
  service:
    name: nginx
    state: restarted
    enabled: true
